name: 刷步数

on:
  schedule:
    - cron: 30 11 * * *
  watch:
    types: started
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间
    steps:
      - name: 继续使用Node16
        env:
             ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
        run: echo ${{ env.ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION }}
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Update system and install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: 初始化Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 执行刷步
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          sckey='${{ secrets.SCKEY }}'
          python3 githubRun.py ${user} ${passwd} ${sckey}
