name: 刷步数

on:
  schedule:
    - cron: 30 11 * * *
  watch:
    types: started
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y

      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 设置环境变量
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          sckey='${{ secrets.SCKEY }}'
          python3 githubRun.py ${user} ${passwd} ${sckey}
