name: Auto Run Steps

on:
  schedule:
    # 北京时间9:00 (UTC 1:00) - 步数1000-10000
    - cron: '0 1 * * *'
    # 北京时间15:00 (UTC 7:00) - 步数15000-25000
    - cron: '0 7 * * *'
    # 北京时间19:30 (UTC 11:30) - 步数30000-40000
    - cron: '30 11 * * *'
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      env:
        USER: ${{ secrets.USER }}
        PWD: ${{ secrets.PWD }}
        SCKEY: ${{ secrets.SCKEY }}
        AES_KEY: ${{ secrets.AES_KEY }}
      run: |
        python main.py
